const fellessanger = [
  {
    tittel: 'Barn av regnbuen',
    lyrics: `Lillebjørn Nilsen`,
    melody: `Pete Seeger`,
    tekst: [
      'En himmel full av stjerner.',
      'Blått hav så langt du ser.',
      'En jord der blomster gror.',
      'Kan du ønske mer?',
      '',
      'Sammen skal vi leve',
      'hver søster og hver bror.',
      'Små barn av regnbuen',
      'og en frodig jord.',
      '',
      'Noen tror det ikke nytter.',
      'Andre kaster tiden bort med prat.',
      'Noen tror at vi kan leve av',
      'plast og syntetisk mat.',
      '',
      'Og noen stjeler fra de unge',
      'som blir sendt ut for å sloss',
      'Noen stjeler fra de mange',
      'som kommer etter oss',
      '',
      'Refreng:',
      'si det til alle barna!',
      'Og si det til hver far og mor:',
      'Ennå har vi en sjanse',
      'til å del e et håp på jord.',
    ],
  },
  {
    tittel: 'Danse mi vise',
    lyrics: `Einar Skjæråsen (1949)`,
    melody: `Torild Goksøyr`,
    tekst: [
      'Vinden blæs synna, og vinden blæs norda',
      'Lyset og skuggen er syskjen på jorda',
      'Sommarn er stutt, og vintern er lang',
      'Danse mi vise, gråte min sang',
      '',
      'Innunder yta glir moldmørke årer',
      'Blåveisen blømer i gråbleke vårer',
      'Livstrua bryt gjennom tela og tvang',
      'Danse mi vise, gråte min sang',
      '',
      'Friarar er vi, om vona er lita',
      "Nynn om 'a Berit, så får du 'a Brita",
      'Drøm på din sten at du sit på et fang',
      'Danse mi vise, gråte min sang',
      '',
      'Somme er fattige, somme er rike',
      'Berre tel slutt er vi jamsis og like',
      'Vegen er lystig, og vegen er vrang',
      'Danse mi vise, gråte min sang',
    ],
  },
  {
    tittel: 'De nære ting',
    lyrics: `A. Paasche Aasen`,
    melody: `Kurt Foss og Reidar Bøe`,
    tekst: [
      'Ditt sinn monne flyve,',
      'Så vide omkring,',
      'Det er som du glemmer,',
      'De nære ting,',
      'Det er som du aldri,',
      'En time har fred,',
      'Du lengter bestandig,',
      'Ett annet sted,',
      '',
      'Du synes dine dager,',
      'Er usle og grå,',
      'Hva er det du søker,',
      'Hva venter du på,',
      'Gå inn i din stue,',
      'Hvor liten den er,',
      'Så rommer den noe,',
      'Ditt hjerte har kjær,',
      '',
      'Den lykken du søker,',
      'Bak blånende fjell,',
      'Kan hende du alltid,',
      'Har eiet den selv,',
      'Du skal ikke jage,',
      'I hvileløs ring,',
      'Men lær deg å elske,',
      'De nære ting,',
    ],
  },
  {
    tittel: 'Den dag kjem aldri',
    lyrics: `Aasmind O. Vinje (1866)`,
    melody: `Norsk folketone`,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1715612869/Sang%20i%20begravelse/Audio/Den_dag_kjem_aldri_womlcw.wav`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'Den dag kjem aldri at eg deg gløymer,',
      'for um eg søver, eg um deg drøymer.',
      'Um nott og dag er du like nær,',
      'og best eg ser deg når myrkt det er.',
      '',
      'Du leikar kringom meg der eg vankar.',
      'Eg høyrer deg når mitt hjarta bankar.',
      'Du støtt meg fylgjer på ferdi mi,',
      'som skuggen gjeng etter soli si.',
      '',
      'I kvar som gjeng og som rid og køyrer,',
      "d'er deg eg ser; deg i alt eg høyrer:",
      'I song og fløyte- og felelåt,',
      'men endå best i min eigen gråt.',
    ],
  },
  {
    tittel: 'Den fyrste song eg høyra fek',
    lyrics: `Per Sivle (1877)`,
    melody: `Lars Søraas (1909)`,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1717675675/Sang%20i%20begravelse/Audio/Den_fyrste_sang_cvgtiv.mp3`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'Den fyrste song eg høyra fekk',
      'Var mor sin song ved vogga',
      'Dei mjuke ord til hjarta gjekk',
      'Dei kunde gråten stogga',
      '',
      'Dei sulla meg so underleg',
      'So stilt og mjukt te sova',
      'Dei synte meg ein fager veg',
      'Opp frå vår vesle stova',
      '',
      'Den vegen ser eg enno tidt',
      'Når eg fær auga kvila',
      'Der stend ein engel smiler blidt',
      'Som berre ei kan smila',
      '',
      'Og når eg sliten trøytnar av',
      'I strid mot alt som veilar',
      'Eg høyrer stilt frå mor si grav',
      'Den song som all ting heilar',
    ],
  },
  {
    tittel: 'Din tanke er fri',
    lyrics: `A. Cranner`,
    melody: `Tysk folketone`,
    tekst: [
      'Din tanke er fri,',
      'Hvem tror du den finner.',
      'Den flykter forbi,',
      'Slik skyggen forsvinner.',
      'Den kan ikke brennes,',
      'Av fiender kjennes.',
      'Og slik vil det alltid bli: din tanke er fri!',
      '',
      'Jeg tenker hva jeg vil,',
      'Mitt ønske bestemmer.',
      'I stillhet blir det til-',
      'I ukjente drømmer.',
      'Min tanke og lengsel vil bryte hver stengsel.',
      'Og slik vil det alltid bli:',
      'Min tanke er fri!',
      '',
      'Og tvinges vi inn bak jernslåtte dører,',
      'Da flykter den vind som tankene fører.',
      'Fordi våre tanker kan rive ned skranker.',
      'Og slik vil det alltid bli:',
      'Vår tanke er fri!',
    ],
  },
  {
    tittel: 'For siste gang',
    lyrics: `Eivind Skeie`,
    melody: `Sigvald Tveit`,
    tekst: [
      'Døren låses porten lukkes',
      'Alt er gjort for aller siste gang',
      'Gi meg hånden før du reiser',
      'Sett deg ganske stille på mitt fang',
      'Om det som er forbi er',
      'Forbi da har jeg noe vakkert å si',
      'Alltid skal jeg huske det vi delte du og jeg',
      'Aldri skal jeg glemme det du var for meg',
      '',
      'Være sammen siden skilles',
      'Det er veien hver og en må gå',
      'La oss ikke være triste',
      'Selv om det er oss det gjelder nå',
      'Om det som er forbi er forbi',
      'Da har jeg noe vakkert å si',
      'Alltid skal jeg huske det vi delte du og jeg',
      'Aldri skal jeg glemme det du var for meg',
      '',
      'Døren låses porten lukkes',
      'Alt er gjort for aller siste gang',
      'Om vi siden aldri møtes',
      'Kan jeg være hos deg i min sang',
      'Om det som er forbi er forbi',
      'Da har jeg noe vakkert å si',
      'Alltid skal jeg huske det vi delte du og jeg',
      'Aldri skal jeg glemme alt du var for meg',
    ],
  },
  {
    tittel: 'Gje meg handa di ven',
    lyrics: `Sondre Bratland (1988)`,
    melody: `Irsk folketone (Down by the Sally Gardens)`,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1717676564/Sang%20i%20begravelse/Audio/Gje_meg_handa_di_ven_juebex.mp3`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'Gje meg handa di ven når det kveldnar,',
      'Det blir mørkt og me treng ei hand,',
      'La dei ljose og vennlege tankar,',
      'Fylgje oss inn i draumars land,',
      'Lat varmen frå ein som er glad i deg,',
      'Tenne stjerner i myrkaste natt,',
      'Gje meg handa di ven når det kveldnar,',
      'Det blir mørkt og me treng ei hand,',
      '',
      'Varme tankar og hender som trøystar,',
      'Er som sol over frosen jord,',
      'Kjenne varmen frå ein som er nær deg,',
      'Gjev langt meire enn store ord,',
      'Lat varmen frå ein som er glad i deg,',
      'Tenne stjerner i mørkaste natt,',
      'Gje meg handa di ven når det kveldar,',
      'Det blir mørkt og me treng ei hand,',
    ],
  },
  {
    tittel: 'Höstvisa',
    lyrics: `Tove Jansson`,
    melody: `Erna Tauro`,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1717670313/Sang%20i%20begravelse/Audio/Ho%CC%88stvisa_Fellessang_f2yo4t.mp3`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'Vägen hem var mycket lång och ingen har jag mött,',
      'nu blir kvällarna kyliga och sena.',
      'Kom trösta mig en smula, för nu är jag ganska trött,',
      'och med ens så förfärligt allena.',
      'Jag märkte aldrig förut, att mörkret är så stort,',
      'går och tänker på allt det där man borde.',
      'Det finns så mycket saker jag skulle sagt och gjort',
      'och det är så väldigt lite jag gjorde.',
      '',
      'Skynda dig älskade, skynda att älska,',
      'dagarna mörkna minut för minut,',
      'tänd våra ljus, det är nära till natten,',
      'snart är den blommande sommarn slut.',
      '',
      'Jag letar efter nånting som vi kanske glömde bort',
      'och som du kunde hjälpa mig att finna.',
      'En sommar går förbi, den är alltid lika kort,',
      'den är drömmen om det man kunde vinna.',
      "Du kommer kanske nån gång, förr'n skymmningen blir blå,",
      'innan ängarna är torra och tomma.',
      'Kanske hittar vi varann, kanske hittar vi då på',
      'något sätt att få allting att blomma.',
      '',
      'Skynda dig älskade, skynda att älska,',
      'dagarna mörkna minut för minut,',
      'tänd våra ljus, det är nära till natten,',
      'snart är den blommande sommarn slut.',
    ],
  },
  {
    tittel: 'Minibarnas sovesang',
    lyrics: ``,
    melody: ``,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1717672120/Sang%20i%20begravelse/Audio/Minibarnas_sovesang_de1jgf.mp3`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'Sove, du skal sove',
      'Mens du hviler, skal jeg våke',
      'Du kan seile inn i Drømmeland',
      'Jeg passer på',
    ],
  },
  {
    tittel: 'Nocturne',
    lyrics: `Evert Taube`,
    melody: `Evert Taube`,
    tekst: [
      'Sov på min arm! Natten gömmer',
      'Under sin vinge din blossande kind',
      'Lycklig och varm snart du drömmer',
      'Flyr mig I drömmen som våg flyr vind',
      '',
      'Fångas igen. Flämtar. Strider',
      'Vill inte. Vill. Och blir åter kysst',
      'Slumra min vän! Natten skrider',
      'Kärleken vaktar dig ömt och tyst',
      '',
      'Sov på min arm! Månens skära',
      'Lyftes ur lundarnas skugga skyggt',
      'Och på din barm o min kära',
      'Täljer dess återglans timmarnas flykt',
      '',
      'Helig den frid hjärtat hyser',
      'Mitt I den virvlande blodströmmens larm!',
      'Slut är din strid. Månen lyser',
      'Vårnattsvind svalkar dig. Sov på min arm',
    ],
  },
  {
    tittel: 'So ro, lille mann',
    lyrics: `Thorbjørn Egner (1952)`,
    melody: `Christian Hartmann (1952)`,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1717678182/Sang%20i%20begravelse/Audio/Sa%CC%8A_ro_lille_mann_mpo4xo.mp3`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'So ro, lille mann',
      'Nå er dagen over',
      'Alle mus i alle land',
      'Ligger nå og sover',
      '',
      'So og ro og tipp på tå',
      'Sov min vesle pode',
      'Reven sover også nå',
      'Med halen under hodet',
    ],
  },
  {
    tittel: 'Så skimrande var aldrig havet',
    lyrics: `Evert Taube`,
    melody: `Evert Taube`,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1717670676/Sang%20i%20begravelse/Audio/Vem_kan_segla_ijybpp.mp3`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'Så skimrande var aldrig havet',
      'Och stranden aldrig så befriande',
      'Fälten ängarna och träden aldrig så vackra',
      'Och blommorna aldrig så ljuvligt doftande',
      'Som när du gick vid min sida',
      'Mot solnedgången aftonen den underbara',
      'Då dina lockar dolde mig för världen',
      'Medan du dränkte alla mina sorger',
      'Älskling,',
      'I din första kyss',
    ],
  },
  {
    tittel: 'Til Ungdommen',
    lyrics: `Nordahl Grieg (1936)`,
    melody: `Otto Mortensen (1952)`,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1717670543/Sang%20i%20begravelse/Audio/Til_ungdommen_wwdgnp.mp3`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'Kringsatt av fiender, gå inn i din tid!',
      'Under en blodig storm – vi deg til strid!',
      'Kanskje du spør i angst, udekket, åpen:',
      'hva skal jeg kjempe med, hva er mitt våpen?',
      '',
      'Her er ditt vern mot vold, her er ditt sverd:',
      'troen på livet vårt, menneskets verd.',
      'For all vår fremtids skyld, søk det og dyrk det,',
      'dø om du må – men: øk det og styrk det!',
      '',
      'Stilt går granatenes glidende bånd.',
      'Stans deres drift mot død, stans dem med ånd!',
      'Krig er forakt for liv. Fred er å skape.',
      'Kast dine krefter inn: døden skal tape!',
      '',
      'Da synker våpnene maktesløs ned!',
      'Skaper vi menneskeverd, skaper vi fred.',
      'Den som med høyre arm bærer en byrde,',
      'dyr og umistelig, kan ikke myrde.',
      '',
      'Dette er løftet vårt fra bror til bror:',
      'vi vil bli gode mot menskenes jord.',
      'Vi vil ta vare på skjønnheten, varmen –',
      'som om vi bar et barn varsomt på armen!',
    ],
  },
  {
    tittel: 'Vem kan segla förutan vind',
    lyrics: `Ukjent`,
    melody: `Svensk folketone`,
    audio: true,
    audioUrl: `https://res.cloudinary.com/dt3k2apqd/video/upload/v1717670676/Sang%20i%20begravelse/Audio/Vem_kan_segla_ijybpp.mp3`,
    performers: ['Nils Georg Nilsen'],
    tekst: [
      'Vem kan segla förutan vind?',
      'Vem kan ro utan åror?',
      'Vem kan skiljas från vännen sin',
      'Utan att fälla tårar?',
      '',
      'Jag kan segla förutan vind',
      'Jag kan ro utan åror',
      'Men ej skiljas från vännen min',
      'Utan att fälla tårar',
    ],
  },
  // More fellessanger...
];

export default fellessanger;
