// salmerData.js
const salmer = [
  {
    tittel: 'Alltid freidig når du går (Salme 415)',
    lyrics: 'Christian Richardt 1867',
    melody: 'C. E. F. Weyse 1938',
    tekst: [
      'Alltid freidig når du går',
      'veier Gud tør kjenne,',
      'selv om du til målet når',
      'først ved verdens ende!',
      '',
      'Aldri redd for mørkets makt!',
      'Stjernene vil lyse;',
      'med et Fadervår i pakt',
      'skal du aldri gyse.',
      '',
      'Kjemp for alt hva du har kjært,',
      'dø om så det gjelder!',
      'Da er livet ei så svært,',
      'døden ikke heller.',
    ],
  },
  {
    tittel: 'Alt ble med ett stille (Salme 875)',
    lyrics: 'Svein Ellingsen (1998)',
    melody: 'Egil Hovland (1998)',
    tekst: [
      'Alt ble med ett så stille,',
      'livet er helt forandret.',
      'Døden har banket på vår dør',
      'og sorgen har fylt hvert rom.',
      '',
      'Hvor det er tungt å miste,',
      'en vi så høyt har elsket!',
      'Å, hvilken tomhet over alt,',
      'vårt savn er så vondt og sårt.',
      '',
      'Mange er våre tårer,',
      'her, blant de tusen spørsmål.',
      'Gud, du som ser vår dype sorg,',
      'vi ber deg: vær du vår trøst!',
      '',
      'Vær hos oss midt i savnet,',
      'omslutt oss med din omsorg.',
      'Gud, ta vår smerte i din hånd,',
      'så uro kan bli til fred.',
      '',
      'Du som er trøstens kilde,',
      'la oss få tro i sorgen:',
      'tro at vi alltid er hos deg,',
      'vår Herre i liv og død.',
    ],
  },
  {
    tittel: 'Amazing grace (Salme 342)',
    lyrics: 'John Newton (1779, 1790)',
    translation: 'Trygve Bjerkrheim (1966)',
    melody: 'Columbian Harmony (1829)',
    tekst: [
      'Amazing grace (how sweet the sound)',
      'that saved a wretch like me!',
      'I once was lost, but now am found,',
      'was blind, but now I see.',
      '',
      "'Twas grace that taught my heart to fear,",
      'and grace my fears relieved;',
      'how precious did that grace appear',
      'the hour I first believed!',
      '',
      'Through many dangers, toils and snares',
      'I have already come:',
      "'tis grace has brought me safe thus far,",
      'and grace will lead me home.',
    ],
  },
  {
    tittel: 'An Irish Blessing',
    lyrics: 'Ukjent',
    melody: 'Irsk folketone',
    tekst: [
      'May the road rise to meet you.',
      'May the wind be always at your back.',
      'May the sun shine warm upon your face,',
      'The rains fall soft upon your fields.',
      '',
      'And until we meet again, until we meet again,',
      'May God hold you in the palm of his hand.',
      'And until we meet again, until we meet again,',
      'May God hold you in the palm of his hand.',
      '',
      'May the sun make your days bright,',
      'May the stars illuminate your nights,',
      'May the flowers bloom along your path,',
      'Your house stand firm against the storm.',
      '',
      'And until we meet again, until we meet again,',
      'May God hold you in the palm of his hand.',
      'And until we meet again, until we meet again,',
      'May God hold you in the palm of his hand.',
    ],
  },
  {
    tittel: 'Blott en dag (Salme 489)',
    lyrics: 'Lina Sandell (1865, 1872)',
    melody: 'Oscar Ahnfelt (1872)',
    tekst: [
      'Blott en dag ett ögonblick i sänder',
      'Vilken tröst vad än som kommer på',
      'Allt ju vilar i min Faders händer',
      'Skulle jag som barn väl ängslas då',
      'Han som bär för mig en Faders hjärta',
      'Giver ju åt varje nyfödd dag',
      'Dess beskärda del av fröjd och smärta',
      'Möda vila och behag',
      '',
      'Själv han är mig alla dagar nära',
      'För var särskild tid med särskild nåd',
      'Varje dags bekymmer vill han bära',
      'Han som heter både Kraft och Råd',
      'Att sin dyra egendom bevara',
      'Denna omsorg har han lagt på sig',
      'Som din dag så skall din kraft ock vara',
      'Detta löfte gav han mig',
      '',
      'Hjälp mig då att vila tryggt och stilla',
      'Blott vid dina löften Herre kär',
      'Ej min tro och ej den tröst förspilla',
      'Som i ordet mig förvarad är',
      'Hjälp mig Herre att vad helst mig händer',
      'Taga ur din trogna fadershand',
      'Blott en dag ett ögonblick i sänder',
      'Tills jag nått det goda land',
    ],
  },
  {
    tittel: 'Blå salme (Salme 832)',
    lyrics: 'Erik Bye (1994)',
    melody: 'Henning Sommerro (1994)',
    tekst: [
      'Jeg synger meg en blå, blå salme',
      'Når dagen svinger hatten til farvel',
      'Og ror med sakte åretak mot strender',
      'Dit alle dager ror når det blir kveld.',
      'Da søker jeg min hvile',
      'Ved treets trygge rot',
      'Mens sankthansormer gløder grønt',
      'I gresset ved min fot.',
      'Da synger jeg min salme.',
      '',
      'Jeg synger meg en blå, blå salme',
      'Og takker for all grøde som ble min.',
      'For lyse døgn, for barneskritt i tunet',
      'Og dine gode kjærtegn mot mitt kinn.',
      'Men òg for våkenetter',
      'Som aldri unte ro',
      'Men gav min dag et dunkelt drag jeg aldri helt forsto.',
      'Da synger jeg min salme.',
      '',
      'Jeg synger meg en blå, blå salme',
      'Til deg, du Hånd som sanker og som sår',
      'Og senker deg med signing over jorden',
      'Med legedom for alle våre sår.',
      'Som byr oss rette ryggen',
      'Stå opp og gå i strid.',
      'Med løftet hode skal hver sjel',
      'Gå inn i Herrens tid.',
      'Så synger vi vår salme.',
    ],
  },
  {
    tittel: 'Bred Dina vida vingar (Salme 819)',
    lyrics: 'Lina Sandell (1865)',
    melody: 'Svensk folketone fra Skåne',
    tekst: [
      'Bred dina vida vingar, o Jesus, över mig',
      'Och låt mig stilla vila i ve och väl hos dig',
      'Bliv du mitt allt i alla, min visdom och mitt råd',
      'Och låt mig alla dagar få leva blott av nåd',
      '',
      'Förlåt mig alla synder och två mig i ditt blod',
      'Giv mig ett heligt sinne, en vilja ny och god',
      'Tag i din vård och hagnad oss alla, stora små',
      'Och låt i frid oss åter till nattens vila gå',
    ],
  },
  {
    tittel: 'Deg være ære, herre over dødens makt! (Salme 197)',
    lyrics: 'Edmond L. Budry (1885)',
    translation: 'Arne Fjellberg (1947)',
    melody: 'G. Fr. Händel (1746)',
    tekst: [
      'Deg være ære, Herre over dødens makt!',
      'Evig skal døden være Kristus underlagt.',
      'Lyset fyller haven, se en engel kom,',
      'åpnet den stengte graven,',
      'Jesu grav er tom!',
      '',
      'Omkved:',
      'Deg være ære,',
      'Herre over dødens makt!',
      'Evig skal døden være',
      'Kristus underlagt.',
      '',
      'Frykt ikke mere! Evig er han med.',
      'Troens øye ser det; Han gir liv og fred.',
      'Kristi navn er ære, seier er hans vei.',
      'Evig skal han regjere, aldri frykter jeg',
      '',
      'Se, Herren lever! Salige morgenstund',
      'Mørkets makter bever. Trygg er troens grunn.',
      'Jubelropet runger; Frelseren er her!',
      'Pris han, alle tunger, Kristus Herre er!',
    ],
  },
  {
    tittel: 'Deg å få skode (Salme 482)',
    lyrics:
      'Irsk fra 700-t, til engelsk Mary Byrne (1905) og Eleanor Hull (1912)',
    translation: 'Arve Brunvoll (1978)',
    melody: 'Irsk folketone',
    tekst: [
      'Deg å få skode er sæla å nå,',
      'Gud, ver det syn som mitt hjarta vil sjå;',
      'ver du for tanken min dyraste skatt,',
      'ljoset som strålar ved dag og ved natt!',
      '',
      'Ver du min visdom, mi sanning og trøyst,',
      'tal du det levande ord med di røyst!',
      'Far, lat meg vere barn her hjå deg.',
      'Kom til meg, Herre, ja bu du i meg!',
      '',
      'Ver du i striden mitt skjold og mitt sverd;',
      'ver du det merke som syner mitt verd,',
      'livd for mi sjel, den tryggaste vakt;',
      'lyft meg mot himlen, du makt i mi makt!',
      '',
      'Rikdom og ære, som menneske gjev,',
      'er ikkje meir enn den morknande vev',
      'Du er min arv som varer til sist,',
      'himmelske konge, det veit eg for visst',
      '',
      'Konge i æva, å lat du meg då,',
      'sigrande inn i ditt rike få gå!',
      'Ver du mi tru, den vona eg ber',
      'til eg får skode din herlegdom der',
    ],
  },
  {
    tittel: 'Deilig er jorden (Salme 48)',
    lyrics: 'B.S. Ingemann (1850)',
    melody: 'Breslau (1842)',
    tekst: [
      'Deilig er jorden,',
      'prektig er Guds himmel,',
      'skjønn er sjelenes pilgrimsgang.',
      'Gjennom de fagre',
      'riker på jorden',
      'går vi til paradis med sang.',
      '',
      'Tider skal komme,',
      'tider skal henrulle,',
      'slekt skal følge slekters gang.',
      'Aldri forstummer',
      'tonen fra himlen',
      'i sjelens glade pilgrimssang.',
      '',
      'Englene sang den,',
      'først for markens hyrder;',
      'skjønt fra sjel til sjel det lød.',
      'Fred over jorden,',
      'menneske fryd deg.',
      'Oss er en evig Frelser født',
    ],
  },
  {
    tittel: 'Deilig er den himmel blå (Salme 90)',
    lyrics: 'N.F.S. Grundsvig (1810)',
    translation: 'Anders Hovden (1900)',
    melody: 'Jacob Gerhard Meidell (1840)',
    tekst: [
      'Deilig er den himmel blå,',
      'lyst det er å se derpå,',
      'hvor de gylne stjerner blinker',
      'hvor de smiler, hvor de vinker',
      'oss fra jorden opp til seg',
      '',
      'Det var midt i julenatt,',
      'hver en stjerne glimtet matt',
      'da med ett der ble å skue',
      'en så klar på himlens bue',
      'som en liten stjernesol',
      '',
      'Denne stjerne lys og mild',
      'som kan aldri lede vill,',
      'er hans guddoms ord det klare,',
      'som han lot oss åpenbare',
      'for å lyse for vår fot',
    ],
  },
  {
    tittel: 'Den fyrste song eg høyra fek',
    lyrics: 'Per Sivle (1877)',
    melody: 'Lars Søraas (1909)',
    tekst: [
      'Den fyrste song eg høyra fekk',
      'Var mor sin song ved vogga',
      'Dei mjuke ord til hjarta gjekk',
      'Dei kunde gråten stogga',
      '',
      'Dei sulla meg so underleg',
      'So stilt og mjukt te sova',
      'Dei synte meg ein fager veg',
      'Opp frå vår vesle stova',
      '',
      'Den vegen ser eg enno tidt',
      'Når eg fær auga kvila',
      'Der stend ein engel smiler blidt',
      'Som berre ei kan smila',
      '',
      'Og når eg sliten trøytnar av',
      'I strid mot alt som veilar',
      'Eg høyrer stilt frå mor si grav',
      'Den song som all ting heilar',
    ],
  },
  {
    tittel: 'Den prektig kledde sommerfugl (Salme 292)',
    lyrics: 'Henrik Wergeland (1840)',
    melody: 'Svensk folketone',
    tekst: [
      'Den prektigkledde sommerfugl',
      'er fløyet fra Guds hånd.',
      'Han ga den gyldne ringer',
      'og røde purpurbånd.',
      '',
      'Han lærte den å flyve høyt,',
      'høyere enn jeg er.',
      'Den har nok fuglens lyster,',
      'men ei dens dun og fjær.',
      '',
      'Og alle verdens mennesker',
      'og alle kongebud',
      'ei gjøre kan en sommerfugl.',
      'Det kan alene Gud',
    ],
  },
  {
    tittel: 'Det er makt i de foldede hender (Salme 631)',
    lyrics: 'Trygve Bjerkrheim (1955)',
    melody: 'Øivind Tønnesen (1962)',
    tekst: [
      'Det er makt i de foldede hender',
      'I seg selv er de svake og små',
      'Men mot allmaktens Gud du dem vender',
      'Han har lovet at svar skal du få',
      'Det er svar underveis',
      'Engler kommer med bud',
      'Om det drøyer',
      'Dog fram det skal nå',
      'For det lovet jo løftenes trofaste Gud',
      'Kall på meg og du hjelpen skal få',
      '',
      'Du som ber for ditt barn dine kjære',
      'Er i forbønn fra år og til år',
      'Om du tålmodets lekse må lære',
      'Himlens bønnesvar engang du får',
      'Det er svar underveis',
      'Engler kommer med bud',
      'Om det drøyer',
      'Dog fram det skal nå',
      'For det lovet jo løftenes trofaste Gud',
      'Kall på meg og du hjelpen skal få',
      '',
      'Det er makt i de foldede hender',
      'Når i frelserens navn du får be',
      'Og en gang når du livsløpet ender',
      'Hvert et bønnesvar klart skal du se',
      'Det er svar underveis',
      'Engler kommer med bud',
      'Om det drøyer',
      'Dog fram det skal nå',
      'For det lovet jo løftenes trofaste Gud',
      'Kall på meg og du hjelpen skal få',
    ],
  },
  {
    tittel: 'Det hev ei rose sprunge (Salme 33)',
    lyrics: 'Tysk (1587), v3 Friedrich Layriz (1844)',
    translation: 'Peter Hognestad (1919, 1921)',
    melody: '1400-t, Köln (1599), Michael Praetorius (1609)',
    tekst: [
      'Det hev ei rose sprunge',
      'Ut av ei rot så grann',
      'Som fedrane hev sunge',
      'Av Jesse rot ho rann',
      'Og var ein blome blid',
      'Midt i den kalde vinter',
      'Ved mørke midtnatts tid',
      '',
      'Guds rose ljuvleg angar',
      'Og skin i jordlivsnatt',
      'Når henner ljos oss fangar',
      'Ho vert vår beste skatt',
      'Me syng i englelag',
      'No er det fødd ein frelsar',
      'Og natta vart til dag',
    ],
  },
  {
    tittel: 'Ein fin liten blome (Salme 492)',
    lyrics: 'Johan Alfred Blomberg (1889)',
    translation: 'Andres Hovden (1927)',
    melody: 'Bjørn Eidsvåg (1969)',
    tekst: [
      'Ein fin liten blome i skogen eg ser,',
      'I granskogen diger og dryg,',
      'Og vent mellom mose og lyng han seg ter.',
      'Han står der så liten og blyg.',
      '',
      'Sei ottast du ikkje i skogen stå gøymd.',
      'Der skuggane tyngje deg må?',
      '-Å nei, for av Herren eg aldri vert gløymd,',
      'til ringaste blom vil han sjå.',
      '',
      'Men ynskjer du ikkje i prydhagen stå,',
      'der folk kunne skoda på deg?',
      '-Å nei, eg trivst best mellom ringe og små,',
      'eg føddest til skogblome eg.',
      '',
      'Som blomen om vinteren visnar eg av,',
      'men gler meg, for då står eg brud.',
      'Lat lekamen kvila med fred i si grav,',
      'mi sjel, ho er heime hos Gud.',
      '',
      'Ja, glad skal eg vakna hos Jesus eingong,',
      'i morgonen ævele klår.',
      'Og blanda med heilage englar min song',
      'i himmele, dit døden ei når!',
    ],
  },
  {
    tittel: 'Fager kveldssol smiler (Salme 817)',
    lyrics: 'A.H.H. Von Fallersleben (1937)',
    translation: 'Peter Hognestad (1904), Ella Holm Bull (1980)',
    melody: 'J. Chr. H. Ring (1927)',
    tekst: [
      'Fager kveldsol smiler over heimen ned,',
      'jord og himmel kviler stilt i heilag fred.',
      '',
      'Berre bekken brusar frå det bratte fjell,',
      'høyr, kor sterkt det susar i den stille kveld.',
      '',
      'Ingen kveld kan læra bekken fred og ro,',
      'ingi klokke bera honom kvilebod.',
      '',
      'Så mitt hjarta stundar bankande i barm',
      'til eg eingong blundar i Guds faderarm.',
    ],
  },
  {
    tittel: 'Fall til ro og kjenn at jeg er Herre (Salme 455)',
    lyrics: 'Wendy Carter (1971)',
    translation: 'Gregers Lunch (1973)',
    melody: 'Wendy Carter (1971)',
    tekst: [
      'Refreng:',
      'Fall til ro, og kjenn at jeg er Herre.',
      'Fall til ro, ja, sett deg bare ned.',
      'Fall til ro og kjenn at jeg er din Gud,',
      'jeg vil gi deg av min fred.',
      '',
      'Søk du først mitt rike,',
      'og sett din lit til meg,',
      'så skal Ånden fra himmelen',
      'falle over deg.',
      'Refreng',
      '',
      'Jeg vil kalle deg til glede,',
      'Jeg vil kalle deg til savn.',
      'Du må legge verden bak deg,',
      'men du skal styrkes i mitt navn.',
      'Refreng',
      '',
      'Jeg vil prise Jesus Kristus,',
      'Jeg vil takke Israels Gud.',
      'Jeg vil lovsynge min Frelser,',
      'som gir meg dette bud.',
      'Refreng',
    ],
  },
  {
    tittel: 'Gje meg handa di ven',
    lyrics: 'Sondre Bratland (1988)',
    melody: 'Irsk Folketone (Down by the Sally Gardens)',
    tekst: [
      'Gje meg handa di ven når det kveldnar',
      'Det blir mørkt og me treng ei hand',
      'La dei ljose og vennlege tankar',
      'Fylgje oss inn i draumars land',
      'Lat varmen frå ein som er glad i deg',
      'Tenne stjerner i myrkaste natt',
      'Gje meg handa di ven',
      'Når det kveldar',
      'Det blir mørkt og me treng ei hand',
      '',
      'Varme tankar og hender som trøystar',
      'Er som sol over frosen jord',
      'Kjenne varmen frå ein som er nær deg',
      'Gjev langt meire enn store ord',
      'Lat varmen frå ein som er glad i deg',
      'Tenne stjerner i mørkaste natt',
      'Gje meg handa di ven når det kveldar',
      'Det blir mørkt og me treng ei hand',
    ],
  },
  {
    tittel: 'Gud når du til oppbrudd kaller (salme 867)',
    lyrics: 'Lyder Brun (1913)',
    melody: 'Ludvik M. Lindeman (1864)',
    tekst: [
      'Gud, når du til oppbrudd kaller,',
      'hele livets dag trer frem:',
      'Barndom, ungdom, moden alder,',
      'arbeid, hvile, gjerning, hjem.',
      'Alt jeg ser i dødens port:',
      'Sorg og glede, smått og stort.',
      '',
      'Takk for alle livets gleder,',
      'tusenfryd ved veiens kant,',
      'takk for sorgens stille steder,',
      'takk for hver en venn jeg vant!',
      'Takk for minner, takk for håp,',
      'takk for smertens bitre dåp!',
      '',
      'Gud, som meg til arbeid kalte,',
      'og som nå meg hvile bød,',
      'du som mine dager talte,',
      'og som gav meg livets brød,',
      'hjelp meg i den siste vakt!',
      'Kle meg i din hvite drakt!',
    ],
  },
  {
    tittel: 'Gud signe vårt dyre fedreland (Salme 757)',
    lyrics: 'Elias Blix (1890)',
    melody: 'C.E.F. Weyse (1826)',
    tekst: [
      'Gud signe vårt dyre fedreland og lat det som hagen bløma!',
      'Lat lysa din fred frå fjell til strand og vetter for vårsol røma!',
      'Lat folket som brøder saman bu, som kristne det kan seg søma!',
      '',
      'Vårt heimland i mørker lenge låg, og vankunna ljoset gøymde.',
      'Men, Gud, du i nåde til oss såg, din kjærleik oss ikkje gløymde.',
      'Du sende ditt ord til Noregs fjell, og ljos over landet strøymde.',
      '',
      'No er det i Noreg atter dag med vårsol og song i skogen.',
      'Om sædet enn gror på ymist lag, det brydder då etter plogen.',
      'Så signe då Gud det gode såd, til groren ein gong er mogen!',
    ],
  },
  {
    tittel: 'Guds kjærleik er som stranda og som graset (Salme 734)',
    lyrics: 'Anders Frostenson (1968)',
    translation: 'Alfred Hauge (1973)',
    melody: 'Lars Åke Lundberg (1968)',
    tekst: [
      'Guds kjærleik er som stranda og som graset',
      'Og vind og vidd og jord og allheims rom',
      'Vi fridom fekk å bu der, gå og koma',
      'Å seia ja til Gud og seia nei',
      'Guds kjærleik er som stranda og som graset',
      'Og vind og vidd og jord og allheims rom',
      '',
      'Vi vil ein fridom der vi er oss sjølve',
      'Ein fridom vi kan gjera noko av',
      'Der ingen tomleik finst, men rom for draumar',
      'Ei jord der tre og blomar kan slå rot',
      'Guds kjærleik er som stranda og som graset',
      'Og vind og vidd og jord og allheims rom',
      '',
    ],
  },
  {
    tittel: 'Herre Gud, ditt dyre navn og ære (Salme 1)',
    lyrics: 'Petter Dass (1698)',
    translation: 'Gustav Jensen (1909)',
    melody: 'Norsk folketone fra Romedal',
    tekst: [
      'Herre Gud, ditt dyre navn og ære',
      'over verden høyt i akt skal være,',
      'og alle sjele, de trette træle,',
      'alt som har mæle, de skal fortelle din ære.',
      '',
      'Gud er Gud, om alle land lå øde,',
      'Gud er Gud, om alle mann var døde.',
      'Om slekter svimler blant stjernestimler',
      'i høye himler utallig vrimler Guds grøde.',
      '',
      'Høye hall og dype dal skal vike,',
      'jord og himmel falle skal tillike,',
      'hvert fjell, hver tinde skal brått forsvinne,',
      'men opp skal rinne, som solen skinne, Guds rike.',
    ],
  },
  {
    tittel: 'Ikke en spurv til jorden (Salme 324)',
    lyrics: 'Ingeborg Prytz Fougner (1948)',
    melody: 'Sigurd Lunde (1973)',
    tekst: [
      'Ikke en spurv til jorden uten at Gud det vet.',
      'Ikke en sjel mot døden uten hans kjærlighet!',
      'Ikke en blomst er visnet, ikke en tåre falt',
      'uten at Gud vet om det, han som er over alt.',
      '',
      'Tro det når stormen herjer bladløse vintertrær!',
      'Tro det når brenning bryter over de nakne skjær!',
      'Tro det når ubeskyttet midt i en kamp du står.',
      'Tro det når helt alene du med en smerte går.',
      '',
      'Tro det når noe brister uten å vokse frem.',
      'Tro det når noen mister det som var alt for dem!',
      'Tro det når håp går under uten å reise seg:',
      'Ikke en spurv til jorden! Det er et ord til deg.',
    ],
  },
  {
    tittel: 'Ingen er så trygg i fare (Salme 488)',
    lyrics: 'Lina Sandell (1856)',
    melody: 'Tysk vise',
    tekst: [
      'Ingen er så trygg i fare',
      'som Guds lille barneskare,',
      'fuglen ei i skjul bak løvet,',
      'stjernen ei høyt over støvet.',
      '',
      'Herren selv vil sine berge.',
      'Han er deres skjold og verge.',
      'Over dem han seg forbarmer,',
      'bærer dem på faderarmer.',
      '',
      'Gled deg da, du lille skare!',
      'Jakobs Gud skal deg bevare.',
      'For hans allmakts ord må alle',
      'fiender til jorden falle.',
      '',
      'Hva han tar, og hva han giver,',
      'samme Fader han forbliver,',
      'og hans mål er dette ene:',
      'Barnets sanne vel alene.',
    ],
  },
  {
    tittel: 'Jeg er en seiler på livets hav (Salme 893)',
    lyrics: 'Henry Albert Tandberg (1909)',
    melody: 'Klaus Østby (1909)',
    tekst: [
      'Jeg er en seiler på livets hav',
      'På tidens skiftende bølge',
      'Den Herre Jesus meg kursen gav',
      'Og denne kurs vil jeg følge',
      'Jeg stevner frem mot de lyse lande',
      'Med livsens trær på de skjønne strande',
      'Hvor evig sol og sommer er',
      '',
      'Iblant jeg seiler for medvinds bør',
      'I andres kjølvann og følge',
      'Som just lik meg denne reise gjør',
      'Hen over jordlivets bølge',
      'Og havet smiler og solen skinner',
      'Min dag så stille og blid henrinner',
      'Mens vinden fyller alle seil',
      '',
      'La ankret falle Jeg er i havn',
      'I ly for brenningens vover',
      'Jeg kaster meg i min Frelsers favn',
      'Han som har hjulpet meg over',
      'Og kjente elskede stemmer kaller',
      'Mens ankret sakte og stille faller',
      'I evighetens lyse land',
    ],
  },
  {
    tittel: 'Jeg er i Herrens hender (Salme 494)',
    lyrics: 'Erling Tobiassen (1932)',
    translation: 'Ella Holm Bull (1990)',
    melody: 'Sigurd Lunde (1947)',
    tekst: [
      'Jeg er i Herrens hender når dagen gryr mot vest',
      'Hver morgen han meg sender sitt ord med lys og trøst',
      'Hva dagen vil meg bringe av glede og av savn',
      'Jeg kan på bønnens vinge få kraft i Jesu navn',
      '',
      'Jeg er i Herrens hender i alt som med meg skjer',
      'I smil og gråt jeg kjenner at Herren er meg nær',
      'Om jeg i dype daler må gå den tunge vei',
      'Fra himlens høye saler Hans øye følger meg',
      '',
      'Jeg er i Herrens hender når dagen dør i vest',
      'Min synd jeg stilt bekjenner for ham min høye gjest',
      'Han gir meg himlens nåde og setter englevakt',
      'For natten han vi råde med hellig guddsomsmakt',
      '',
      'Jeg er i Herrens hender når dødsens bud meg når',
      'Mens lyset stilt nedbrenner fra ham jeg hilsen får',
      'Han gir meg stav i hånde han gir meg trøst i sinn',
      'Og glemt er ve og vånde på vei til himlen inn',
    ],
  },
  {
    tittel: 'Kjære gud jeg har det godt (Salme 773)',
    lyrics: 'Margrethe Munthe',
    translation: 'Ingolf Kvamen (1970)',
    melody: 'Jacob Gerhard Meidell (1840)',
    tekst: [
      'Kjære Gud jeg har det godt',
      'Takk for alt som jeg har fått',
      'Du er god Du holder av meg',
      'Kjære Gud gå aldri fra meg',
      'Pass på liten og på stor',
      'Gud bevare far og mor (og alle barn på jorden)',
    ],
  },
  {
    tittel: 'Kjærlighet er lysets kilde (Salme 233)',
    lyrics: 'N.F.S. Grundsvig (1853)',
    melody: 'Ludvik M. Lindeman (1862)',
    tekst: [
      'Kjærlighet er lysets kilde,',
      'kjærlighet er livets rot.',
      'Derfor er Guds råd så milde,',
      'derfor er Guds Ånd så god.',
      'Jesus har den selv forklaret,',
      'Ånden har den åpenbaret,',
      'den kan kjennes i Guds fred',
      'og det håp vi trøstes ved.',
      '',
      'Kjærlighet er livets krone,',
      'kjærlighet er lysets glans.',
      'Derfor sitter på Guds trone',
      'Jesus nå med strålekrans,',
      'han som lyset er og livet,',
      'har for oss seg selv hengivet,',
      'han forblir og lever ved',
      'Guds, sin Faders kjærlighet.',
      '',
      'Kjærlighet er lovens fylde',
      'og fullkommenhetens bånd,',
      'den er hva vår Gud vi skylder,',
      'den er frukten av hans Ånd.',
      'Derfor med Guds-kjærligheten',
      'vokser opp om kapp Guds-freden.',
      'Vi skal også bli ved den',
      'ett med sjelens beste venn.',
    ],
  },
  {
    tittel: 'Kjærlighet fra gud (Salme 651)',
    lyrics: 'J.N.L. Schjørring (1854)',
    translation: 'Knut Tore Andersen (1989)',
    melody: 'H.S. Thompson (1852)',
    tekst: [
      'Kjærlighet fra Gud',
      'Springer like ut',
      'Som en kilde klar og ren.',
      'I dens stille bunn,',
      'I dens dype grunn',
      'Gjemmes livets edelsten.',
      '',
      'Kjærlighet fra Gud',
      'Som en yndig brud',
      'Kommer smykket til oss ned.',
      'Lukk kun opp din favn,',
      'Kom i Jesu navn,',
      'Himlen bringer den jo med.',
      '',
      'Kjærlighet fra Gud',
      'Er det store bud,',
      'Er det eneste jeg vet.',
      'Bli i kjærlighet,',
      'Og du har Guds fred,',
      'For Gud selv er kjærlighet.',
    ],
  },
  {
    tittel: 'Lei, milde ljos (Salme 858)',
    lyrics: 'J.H. Newman (1833)',
    translation: 'Peter Hognestad (1914)',
    melody: 'Charles H. Purday (1860)',
    tekst: [
      'Lei, milde ljos, igjennom skoddeeim,',
      'lei du meg fram!',
      'Eg går i mørke natt langt frå min heim,',
      'lei du meg fram!',
      'Før du min fot; eg treng ei sjå min veg',
      'så langt og vidt - eitt steg er nok åt meg.',
      '',
      'Du veit det vel, eg bad ei alltid så:',
      'Lei du meg fram!',
      'Eg ville velja sjølv min veg, men no',
      'lei du meg fram!',
      'Eg ville leva fritt, var stolt og strid',
      'og stor i mod - å, gløym den dårskaps tid!',
      '',
      'Di makt hev signa meg, då veit eg visst:',
      'Du leier enn',
      'i myr og fjell og hei, og så til sist',
      'ein morgon renn,',
      'då til meg smiler engleåsyn blid,',
      'som eg hev elska før, men mist ei tid.',
    ],
  },
  {
    tittel: 'Mitt hjerte alltid vanker (Salme 38)',
    lyrics: 'Hans Adolph Brorson (1732)',
    translation:
      'Paul Gælok (1908), Knut Tore Andersen (1996), Terje Aronsen (1998)',
    melody: 'Svensk/norsk folketone',
    tekst: [
      'Mitt hjerte alltid vanker i Jesu føderom,',
      'der samles mine tanker som i en hovedsum.',
      'Der er min lengsel hjemme, der har min tro sin skatt;',
      'jeg kan deg aldri glemme, velsignet julenatt!',
      'Den mørke stall skal være mitt hjertes frydeslott,',
      'der kan jeg daglig lære å glemme verdens spott.',
      'Der kan med takk jeg finne hvori min ros består,',
      'når Jesu krybbes minne meg rett til hjerte går.',
      'Akk, kom, jeg opp vil lukke mitt hjerte og mitt sinn',
      'og full av lengsel sukke: Kom, Jesus, dog herinn!',
      'Det er ei fremmed bolig, du har den selv jo kjøpt,',
      'så skal du blive trolig her i mitt hjerte svøpt.',
      'Jeg gjerne palmegrene vil om din krybbe strø,',
      'for deg, for deg alene jeg leve vil og dø.',
      'Kom, la min sjel dog finne sin rette gledes stund,',
      'at du er født herinne i hjertets dype grunn!',
    ],
  },
  {
    tittel: 'Morning has broken (Salme 801)',
    lyrics: 'Eleanor Farjeon (1931)',
    translation: 'Eivind Skeie (1980), Anders Frostenson (1976)',
    melody: 'Gælisk folketone',
    tekst: [
      'Morning has broken like the first morning,',
      'Blackbird has spoken like the first bird,',
      'Praise for the singing, praise for the morning,',
      'Praise for them springing fresh from the world',
      '',
      'Sweet the rain’s new fall, sunlit from Heaven',
      'Like the first dewfall on the first grass',
      'Praise for the sweetness of the wet garden',
      'Sprung in completeness where his feet pass',
      '',
      'Mine is the sunlight, mine is the morning',
      'Born of the one light Eden saw play',
      'Praise with elation, praise every morning',
      'God’s recreation of the new day',
    ],
  },
  {
    tittel: 'Måne og sol (Salme 240)',
    lyrics: 'Britt G. Hallqvist (1973)',
    translation: 'Arve Brunvoll (1977)',
    melody: 'Egil Hovland (1974)',
    tekst: [
      'Måne og sol, skyer og vind',
      'og blomster og barn skapte vår Gud.',
      'Himmel og jord, allting er hans,',
      'Herren vår Gud vil vi takke.',
      '',
      'Refr.:',
      'Herre, vi takker deg, Herre, vi priser deg,',
      'Herre, vi synger ditt hellige navn!.',
      '',
      'Jesus, Guds Sønn, død på et kors',
      'for alle, for oss, lever i dag.',
      'Ja, han er her, ja, han er her,',
      'Herren vår Gud vil vi takke.',
      '',
      'Ånden, vår trøst, levende varm',
      'og hellig og sterk, taler om Gud,',
      'bærer oss frem dag etter dag.',
      'Herren vår Gud vil vi takke.',
    ],
  },
  // More salmer...
];

export default salmer;
