// salmerData.js
const salmer = [
  {
    tittel: 'Alltid freidig når du går (Salme 415)',
    lyrics: 'Christian Richardt 1867',
    melody: 'C. E. F. Weyse 1938',
    tekst: [
      'Alltid freidig når du går',
      'veier Gud tør kjenne,',
      'selv om du til målet når',
      'først ved verdens ende!',
      '',
      'Aldri redd for mørkets makt!',
      'Stjernene vil lyse;',
      'med et Fadervår i pakt',
      'skal du aldri gyse.',
      '',
      'Kjemp for alt hva du har kjært,',
      'dø om så det gjelder!',
      'Da er livet ei så svært,',
      'døden ikke heller.',
    ],
  },
  {
    tittel: 'Alt ble med ett stille (Salme 875)',
    lyrics: 'Svein Ellingsen (1998)',
    melody: 'Egil Hovland (1998)',
    tekst: [
      'Alt ble med ett så stille,',
      'livet er helt forandret.',
      'Døden har banket på vår dør',
      'og sorgen har fylt hvert rom.',
      '',
      'Hvor det er tungt å miste,',
      'en vi så høyt har elsket!',
      'Å, hvilken tomhet over alt,',
      'vårt savn er så vondt og sårt.',
      '',
      'Mange er våre tårer,',
      'her, blant de tusen spørsmål.',
      'Gud, du som ser vår dype sorg,',
      'vi ber deg: vær du vår trøst!',
      '',
      'Vær hos oss midt i savnet,',
      'omslutt oss med din omsorg.',
      'Gud, ta vår smerte i din hånd,',
      'så uro kan bli til fred.',
      '',
      'Du som er trøstens kilde,',
      'la oss få tro i sorgen:',
      'tro at vi alltid er hos deg,',
      'vår Herre i liv og død.',
    ],
  },
  {
    tittel: 'Amazing grace (Salme 342)',
    lyrics: 'John Newton (1779, 1790)',
    translation: 'Trygve Bjerkrheim (1966)',
    melody: 'Columbian Harmony (1829)',
    tekst: [
      'Amazing grace (how sweet the sound)',
      'that saved a wretch like me!',
      'I once was lost, but now am found,',
      'was blind, but now I see.',
      '',
      "'Twas grace that taught my heart to fear,",
      'and grace my fears relieved;',
      'how precious did that grace appear',
      'the hour I first believed!',
      '',
      'Through many dangers, toils and snares',
      'I have already come:',
      "'tis grace has brought me safe thus far,",
      'and grace will lead me home.',
    ],
  },
  {
    tittel: 'An Irish Blessing',
    lyrics: 'Ukjent',
    melody: 'Irsk folketone',
    tekst: [
      'May the road rise to meet you.',
      'May the wind be always at your back.',
      'May the sun shine warm upon your face,',
      'The rains fall soft upon your fields.',
      '',
      'And until we meet again, until we meet again,',
      'May God hold you in the palm of his hand.',
      'And until we meet again, until we meet again,',
      'May God hold you in the palm of his hand.',
      '',
      'May the sun make your days bright,',
      'May the stars illuminate your nights,',
      'May the flowers bloom along your path,',
      'Your house stand firm against the storm.',
      '',
      'And until we meet again, until we meet again,',
      'May God hold you in the palm of his hand.',
      'And until we meet again, until we meet again,',
      'May God hold you in the palm of his hand.',
    ],
  },
  {
    tittel: 'Blott en dag (Salme 489)',
    lyrics: 'Lina Sandell (1865, 1872)',
    melody: 'Oscar Ahnfelt (1872)',
    tekst: [
      'Blott en dag ett ögonblick i sänder',
      'Vilken tröst vad än som kommer på',
      'Allt ju vilar i min Faders händer',
      'Skulle jag som barn väl ängslas då',
      'Han som bär för mig en Faders hjärta',
      'Giver ju åt varje nyfödd dag',
      'Dess beskärda del av fröjd och smärta',
      'Möda vila och behag',
      '',
      'Själv han är mig alla dagar nära',
      'För var särskild tid med särskild nåd',
      'Varje dags bekymmer vill han bära',
      'Han som heter både Kraft och Råd',
      'Att sin dyra egendom bevara',
      'Denna omsorg har han lagt på sig',
      'Som din dag så skall din kraft ock vara',
      'Detta löfte gav han mig',
      '',
      'Hjälp mig då att vila tryggt och stilla',
      'Blott vid dina löften Herre kär',
      'Ej min tro och ej den tröst förspilla',
      'Som i ordet mig förvarad är',
      'Hjälp mig Herre att vad helst mig händer',
      'Taga ur din trogna fadershand',
      'Blott en dag ett ögonblick i sänder',
      'Tills jag nått det goda land',
    ],
  },
  {
    tittel: 'Blå salme (Salme 832)',
    lyrics: 'Erik Bye (1994)',
    melody: 'Henning Sommerro (1994)',
    tekst: [
      'Jeg synger meg en blå, blå salme',
      'Når dagen svinger hatten til farvel',
      'Og ror med sakte åretak mot strender',
      'Dit alle dager ror når det blir kveld.',
      'Da søker jeg min hvile',
      'Ved treets trygge rot',
      'Mens sankthansormer gløder grønt',
      'I gresset ved min fot.',
      'Da synger jeg min salme.',
      '',
      'Jeg synger meg en blå, blå salme',
      'Og takker for all grøde som ble min.',
      'For lyse døgn, for barneskritt i tunet',
      'Og dine gode kjærtegn mot mitt kinn.',
      'Men òg for våkenetter',
      'Som aldri unte ro',
      'Men gav min dag et dunkelt drag jeg aldri helt forsto.',
      'Da synger jeg min salme.',
      '',
      'Jeg synger meg en blå, blå salme',
      'Til deg, du Hånd som sanker og som sår',
      'Og senker deg med signing over jorden',
      'Med legedom for alle våre sår.',
      'Som byr oss rette ryggen',
      'Stå opp og gå i strid.',
      'Med løftet hode skal hver sjel',
      'Gå inn i Herrens tid.',
      'Så synger vi vår salme.',
    ],
  },
  {
    tittel: 'Bred Dina vida vingar (Salme 819)',
    lyrics: 'Lina Sandell (1865)',
    melody: 'Svensk folketone fra Skåne',
    tekst: [
      'Bred dina vida vingar, o Jesus, över mig',
      'Och låt mig stilla vila i ve och väl hos dig',
      'Bliv du mitt allt i alla, min visdom och mitt råd',
      'Och låt mig alla dagar få leva blott av nåd',
      '',
      'Förlåt mig alla synder och två mig i ditt blod',
      'Giv mig ett heligt sinne, en vilja ny och god',
      'Tag i din vård och hagnad oss alla, stora små',
      'Och låt i frid oss åter till nattens vila gå',
    ],
  },
  {
    tittel: 'Deg være ære, herre over dødens makt! (Salme 197)',
    lyrics: 'Edmond L. Budry (1885)',
    translation: 'Arne Fjellberg (1947)',
    melody: 'G. Fr. Händel (1746)',
    tekst: [
      'Deg være ære, Herre over dødens makt!',
      'Evig skal døden være Kristus underlagt.',
      'Lyset fyller haven, se en engel kom,',
      'åpnet den stengte graven,',
      'Jesu grav er tom!',
      '',
      'Omkved:',
      'Deg være ære,',
      'Herre over dødens makt!',
      'Evig skal døden være',
      'Kristus underlagt.',
      '',
      'Frykt ikke mere! Evig er han med.',
      'Troens øye ser det; Han gir liv og fred.',
      'Kristi navn er ære, seier er hans vei.',
      'Evig skal han regjere, aldri frykter jeg',
      '',
      'Se, Herren lever! Salige morgenstund',
      'Mørkets makter bever. Trygg er troens grunn.',
      'Jubelropet runger; Frelseren er her!',
      'Pris han, alle tunger, Kristus Herre er!',
    ],
  },
  {
    tittel: 'Deg å få skode (Salme 482)',
    lyrics:
      'Irsk fra 700-t, til engelsk Mary Byrne (1905) og Eleanor Hull (1912)',
    translation: 'Arve Brunvoll (1978)',
    melody: 'Irsk folketone',
    tekst: [
      'Deg å få skode er sæla å nå,',
      'Gud, ver det syn som mitt hjarta vil sjå;',
      'ver du for tanken min dyraste skatt,',
      'ljoset som strålar ved dag og ved natt!',
      '',
      'Ver du min visdom, mi sanning og trøyst,',
      'tal du det levande ord med di røyst!',
      'Far, lat meg vere barn her hjå deg.',
      'Kom til meg, Herre, ja bu du i meg!',
      '',
      'Ver du i striden mitt skjold og mitt sverd;',
      'ver du det merke som syner mitt verd,',
      'livd for mi sjel, den tryggaste vakt;',
      'lyft meg mot himlen, du makt i mi makt!',
      '',
      'Rikdom og ære, som menneske gjev,',
      'er ikkje meir enn den morknande vev',
      'Du er min arv som varer til sist,',
      'himmelske konge, det veit eg for visst',
      '',
      'Konge i æva, å lat du meg då,',
      'sigrande inn i ditt rike få gå!',
      'Ver du mi tru, den vona eg ber',
      'til eg får skode din herlegdom der',
    ],
  },
  {
    tittel: 'Deilig er jorden (Salme 48)',
    lyrics: 'B.S. Ingemann (1850)',
    melody: 'Breslau (1842)',
    tekst: [
      'Deilig er jorden,',
      'prektig er Guds himmel,',
      'skjønn er sjelenes pilgrimsgang.',
      'Gjennom de fagre',
      'riker på jorden',
      'går vi til paradis med sang.',
      '',
      'Tider skal komme,',
      'tider skal henrulle,',
      'slekt skal følge slekters gang.',
      'Aldri forstummer',
      'tonen fra himlen',
      'i sjelens glade pilgrimssang.',
      '',
      'Englene sang den,',
      'først for markens hyrder;',
      'skjønt fra sjel til sjel det lød.',
      'Fred over jorden,',
      'menneske fryd deg.',
      'Oss er en evig Frelser født',
    ],
  },
  {
    tittel: 'Deilig er den himmel blå (Salme 90)',
    lyrics: 'N.F.S. Grundsvig (1810)',
    translation: 'Anders Hovden (1900)',
    melody: 'Jacob Gerhard Meidell (1840)',
    tekst: [
      'Deilig er den himmel blå,',
      'lyst det er å se derpå,',
      'hvor de gylne stjerner blinker',
      'hvor de smiler, hvor de vinker',
      'oss fra jorden opp til seg',
      '',
      'Det var midt i julenatt,',
      'hver en stjerne glimtet matt',
      'da med ett der ble å skue',
      'en så klar på himlens bue',
      'som en liten stjernesol',
      '',
      'Denne stjerne lys og mild',
      'som kan aldri lede vill,',
      'er hans guddoms ord det klare,',
      'som han lot oss åpenbare',
      'for å lyse for vår fot',
    ],
  },
  {
    tittel: 'Den fyrste song eg høyra fek',
    lyrics: 'Per Sivle (1877)',
    melody: 'Lars Søraas (1909)',
    tekst: [
      'Den fyrste song eg høyra fekk',
      'Var mor sin song ved vogga',
      'Dei mjuke ord til hjarta gjekk',
      'Dei kunde gråten stogga',
      '',
      'Dei sulla meg so underleg',
      'So stilt og mjukt te sova',
      'Dei synte meg ein fager veg',
      'Opp frå vår vesle stova',
      '',
      'Den vegen ser eg enno tidt',
      'Når eg fær auga kvila',
      'Der stend ein engel smiler blidt',
      'Som berre ei kan smila',
      '',
      'Og når eg sliten trøytnar av',
      'I strid mot alt som veilar',
      'Eg høyrer stilt frå mor si grav',
      'Den song som all ting heilar',
    ],
  },
  {
    tittel: 'Den prektig kledde sommerfugl (Salme 292)',
    lyrics: 'Henrik Wergeland (1840)',
    melody: 'Svensk folketone',
    tekst: [
      'Den prektigkledde sommerfugl',
      'er fløyet fra Guds hånd.',
      'Han ga den gyldne ringer',
      'og røde purpurbånd.',
      '',
      'Han lærte den å flyve høyt,',
      'høyere enn jeg er.',
      'Den har nok fuglens lyster,',
      'men ei dens dun og fjær.',
      '',
      'Og alle verdens mennesker',
      'og alle kongebud',
      'ei gjøre kan en sommerfugl.',
      'Det kan alene Gud',
    ],
  },
  {
    tittel: 'Det er makt i de foldede hender (Salme 631)',
    lyrics: 'Trygve Bjerkrheim (1955)',
    melody: 'Øivind Tønnesen (1962)',
    tekst: [
      'Det er makt i de foldede hender',
      'I seg selv er de svake og små',
      'Men mot allmaktens Gud du dem vender',
      'Han har lovet at svar skal du få',
      'Det er svar underveis',
      'Engler kommer med bud',
      'Om det drøyer',
      'Dog fram det skal nå',
      'For det lovet jo løftenes trofaste Gud',
      'Kall på meg og du hjelpen skal få',
      '',
      'Du som ber for ditt barn dine kjære',
      'Er i forbønn fra år og til år',
      'Om du tålmodets lekse må lære',
      'Himlens bønnesvar engang du får',
      'Det er svar underveis',
      'Engler kommer med bud',
      'Om det drøyer',
      'Dog fram det skal nå',
      'For det lovet jo løftenes trofaste Gud',
      'Kall på meg og du hjelpen skal få',
      '',
      'Det er makt i de foldede hender',
      'Når i frelserens navn du får be',
      'Og en gang når du livsløpet ender',
      'Hvert et bønnesvar klart skal du se',
      'Det er svar underveis',
      'Engler kommer med bud',
      'Om det drøyer',
      'Dog fram det skal nå',
      'For det lovet jo løftenes trofaste Gud',
      'Kall på meg og du hjelpen skal få',
    ],
  },
  {
    tittel: 'Det hev ei rose sprunge (Salme 33)',
    lyrics: 'Tysk (1587), v3 Friedrich Layriz (1844)',
    translation: 'Peter Hognestad (1919, 1921)',
    melody: '1400-t, Köln (1599), Michael Praetorius (1609)',
    tekst: [
      'Det hev ei rose sprunge',
      'Ut av ei rot så grann',
      'Som fedrane hev sunge',
      'Av Jesse rot ho rann',
      'Og var ein blome blid',
      'Midt i den kalde vinter',
      'Ved mørke midtnatts tid',
      '',
      'Guds rose ljuvleg angar',
      'Og skin i jordlivsnatt',
      'Når henner ljos oss fangar',
      'Ho vert vår beste skatt',
      'Me syng i englelag',
      'No er det fødd ein frelsar',
      'Og natta vart til dag',
    ],
  },
  // More salmer...
];

export default salmer;
